services:
  - type: web
    name: cleaning-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python cleaning_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
